{
 "title": "Data viz Tweet&Crypto",
 "time": { "from": "2022-11-16T18:05:30.356Z", "to": "2022-11-16T20:39:15.373Z" },
 "panels": [
  {
   "title": "XRP",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Tweets" } },
   "targets": [
    {
     "target": "db.results.aggregate([\n{\"$match\": { \"crypto_name\" : \"xrp\" }},\n{\"$project\": { \"name\" : \"$crypto_name\", \"value\": \"$nbr_tweets\", \"ts\" : \"$datetime\", \"_id\" : 0}}\n])",
     "type": "timeserie"
    },
    {
     "target": "db.cryptos.aggregate([\n{\"$match\": { \"name\" :\"ripple\" }},\n{\"$project\": { \"name\" : \"$name\", \"value\": \"$value\", \"ts\" : \"$date\", \"_id\" : 0}}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "DOT",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Tweets" } },
   "targets": [
    {
     "target": "db.results.aggregate([\n{\"$match\": { \"crypto_name\" : \"dot\" }},\n{\"$project\": { \"name\" : \"$crypto_name\", \"value\": \"$nbr_tweets\", \"ts\" : \"$datetime\", \"_id\" : 0}}\n])",
     "type": "timeserie"
    },
    {
     "target": "db.cryptos.aggregate([\n{\"$match\": { \"name\" :\"polkadot\" }},\n{\"$project\": { \"name\" : \"$name\", \"value\": \"$value\", \"ts\" : \"$date\", \"_id\" : 0}}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "CRO",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Tweets" } },
   "targets": [
    {
     "target": "db.results.aggregate([\n{\"$match\": { \"crypto_name\" : \"cro\" }},\n{\"$project\": { \"name\" : \"$crypto_name\", \"value\": \"$nbr_tweets\", \"ts\" : \"$datetime\", \"_id\" : 0}}\n])",
     "type": "timeserie"
    },
    {
     "target": "db.cryptos.aggregate([\n{\"$match\": { \"name\" :\"crypto-com-chain\" }},\n{\"$project\": { \"name\" : \"$name\", \"value\": \"$value\", \"ts\" : \"$date\", \"_id\" : 0}}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Chiliz",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Tweets" } },
   "targets": [
    {
     "target": "db.results.aggregate([\n{\"$match\": { \"crypto_name\" : \"chz\" }},\n{\"$project\": { \"name\" : \"$crypto_name\", \"value\": \"$nbr_tweets\", \"ts\" : \"$datetime\", \"_id\" : 0}}\n])",
     "type": "timeserie"
    },
    {
     "target": "db.cryptos.aggregate([\n{\"$match\": { \"name\" :\"chiliz\" }},\n{\"$project\": { \"name\" : \"$name\", \"value\": \"$value\", \"ts\" : \"$date\", \"_id\" : 0}}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "SOL",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Tweets" } },
   "targets": [
    {
     "target": "db.results.aggregate([\n{\"$match\": { \"crypto_name\" : \"sol\" }},\n{\"$project\": { \"name\" : \"$crypto_name\", \"value\": \"$nbr_tweets\", \"ts\" : \"$datetime\", \"_id\" : 0}}\n])",
     "type": "timeserie"
    },
    {
     "target": "db.cryptos.aggregate([\n{\"$match\": { \"name\" :\"solana\" }},\n{\"$project\": { \"name\" : \"$name\", \"value\": \"$value\", \"ts\" : \"$date\", \"_id\" : 0}}\n])",
     "type": "timeserie"
    }
   ]
  }
 ]
}